### PR TITLE
Pull Request Grupo 9 com revisão pelo grupo 4 e 7

### PR DESCRIPTION
**Pull request by eduardoparaiso**
Minha parte do projeto refere-se ao Controle de qualidade, como cada produto e funcionário podem ter n problemas associados, precisei adicionar um ICollection do meu modelo ao modelo de vocês (Product e Employee). Por favor verifiquem e não havendo problemas para vocês aceitem o pull request.

### CODE REVIEW

**Review by Azevedo183 — APPROVED** [review]
Pela parte do Employee esta tudo tranquilo, qualquer coisa que for precisso esta a vontade

**Comment by Andredzao** [comment]
Olá Eduardo, desculpa a demora da resposta, mas pareceu-me que estás a tentar criar uma tabela intermédia para precisares de utilizar o ICollection correto? A minha dúvida é qual seria a tabela intermédia, porque pelo que vi estás a utilizar o ICollection para fazer ligação a uma tabela (Issue) que não é intermédia. Posso estar a fazer confusão, por isso agradecia se conseguisses explicar melhor ou rever o que foi feito.
Cumprimentos
________________________________
De: Eduardo Paraíso ***@***.***>
Enviado: 14 de dezembro de 2023 09:47
Para: noellopes/Supermarket ***@***.***>
Cc: André Antunes ***@***.***>; Review requested ***@***.***>
Assunto: [noellopes/Supermarket] Pull Request Grupo 9 com revisão pelo grupo 4 e 7 (PR #59)


Minha parte do projeto refere-se ao Controle de qualidade, como cada produto e funcionário podem ter n problemas associados, precisei adicionar um ICollection do meu modelo ao modelo de vocês (Product e Employee). Por favor verifiquem e não havendo problemas para vocês aceitem o pull request.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/noellopes/Supermarket/pull/59

Commit Summary

  *   24e8baf<https://github.com/noellopes/Supermarket/pull/59/commits/24e8bafa4dc68b70b45270f1ee0d37ee400a0efd> Comma missing
  *   6b734e8<https://github.com/noellopes/Supermarket/pull/59/commits/6b734e82307cd55bd2fd93afbe9057a84231a0d7> Merge branch 'Group9' of https://github.com/noellopes/Supermarket into Group9
  *   014c769<https://github.com/noellopes/Supermarket/pull/59/commits/014c769bcbeb116717775dc634764034a62c5a31> Add verification if already deleted
  *   c1abaf1<https://github.com/noellopes/Supermarket/pull/59/commits/c1abaf12977001c21d3caaa06e906e45f6838dad> If data doesn't exist anymore, return a view with a message
  *   a321fbe<https://github.com/noellopes/Supermarket/pull/59/commits/a321fbe75e06b9fbe63b27729cd2edc35fadd82e> Add message for deletetion
  *   c461d49<https://github.com/noellopes/Supermarket/pull/59/commits/c461d4959baa56fb77b2024e7f12439a53edf5ca> Minor changes
  *   43f3f96<https://github.com/noellopes/Supermarket/pull/59/commits/43f3f96f8f999c1efe16a7273ca15706e4c1e436> Merge branch 'Group9' of https://github.com/noellopes/Supermarket into Group9
  *   25aaddf<https://github.com/noellopes/Supermarket/pull/59/commits/25aaddf486e49584fb4606bc37371b4d972cb803> Update database SupermarketDbContext
  *   7c5cdce<https://github.com/noellopes/Supermarket/pull/59/commits/7c5cdce0fc5d513fd03fc3806d9eb932e0456399> Add Supplier
  *   b1782a4<https://github.com/noellopes/Supermarket/pull/59/commits/b1782a49fd4f841d2f0d01bf426a765d4de06e7a> Add Employee and Product to Issue Creation
  *   508e85f<https://github.com/noellopes/Supermarket/pull/59/commits/508e85f8bc821b9c347087ba3b0c5e19177a2928> Modify Issue Select List
  *   00dcbb6<https://github.com/noellopes/Supermarket/pull/59/commits/00dcbb69db002a017cfcfc0cb7aa034247f89067> Modify Issue Select List
  *   c0c6f01<https://github.com/noellopes/Supermarket/pull/59/commits/c0c6f01c1c7881b6729693feb60da1df755d3e62> Merge branch 'Group9' of https://github.com/noellopes/Supermarket into Group9
  *   df974a6<https://github.com/noellopes/Supermarket/pull/59/commits/df974a6c5eb53eea2a5e885fae2faaa4b4e8204b> Delete messages added

File Changes

(18 files<https://github.com/noellopes/Supermarket/pull/59/files>)

  *   M Controllers/IssuesController.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-36b98b4c44ff9ad5e22fbc03bc0e97d4bc15b24699ecc5ab2f1a04f55da9d204> (36)
  *   M Controllers/ProductExpirationsController.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-8059e068a32d051c9bdce2a8a604600417bfc349922f55a291e3507a7693e1c8> (9)
  *   D Data/Migrations/Application/ApplicationDbContextModelSnapshot.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-f3a82273adfdd3298af89ca81c57d13dcfec6167edf01df20b457de1193cba0f> (276)
  *   R Migrations/20231213170413_updateProductExpirationTable.Designer.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-0ae344a23c7bb22d17bc05aefbabbf990e26fe17ab1cd9a86431bce895e700b3> (10)
  *   R Migrations/20231213170413_updateProductExpirationTable.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-9b4f3ee479a787565f71a10ce4933897cd73ccfed8fef0e44869130603591ac4> (6)
  *   R Migrations/SupermarketDbContextModelSnapshot.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-2e3a2e4bee9f092091e50239f9db02624c6251dfb983ec06223ebce96e1f1abf> (6)
  *   M Models/Employee.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-f972dd3657226491daaf7f5b30a33aa50a920f225533cc1734104d9f568b6444> (2)
  *   M Models/Issue.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-8c066687ade886cebb46da9ea408ff7d8a67650f380d57cf39ff8dcc2e0a639e> (23)
  *   M Models/Product.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-efac43bec618f8d3b31cc8911d4706d8c174d92bba7a3f2dca27473369d57323> (3)
  *   M Models/ProductExpiration.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-1332de60cce1dd1b2f00e19e560145121dbcff885b6808d06e83011592f07fac> (4)
  *   A Models/Supplier.cs<https://github.com/noellopes/Supermarket/pull/59/files#diff-ff16da94e84ec0e5d5bf3ea1b1017ee12927a112810d6a4533c4b77b7f178d9d> (13)
  *   M Views/Issues/Create.cshtml<https://github.com/noellopes/Supermarket/pull/59/files#diff-2d47f44712cfb1e0aaf7cf3e889480c810b45dae25cd82a10388f90839af0b35> (20)
  *   M Views/Issues/Delete.cshtml<https://github.com/noellopes/Supermarket/pull/59/files#diff-e737a18f804b123cb5da31faebe896c0ad2666db35da7c2258ba7b5aeaab8a0b> (36)
  *   M Views/Issues/Details.cshtml<https://github.com/noellopes/Supermarket/pull/59/files#diff-ea86c704b7cd330870c00e41ccb889ac347bbde09eebafa7f82f9cbea0203159> (18)
  *   M Views/Issues/Edit.cshtml<https://github.com/noellopes/Supermarket/pull/59/files#diff-475205f2fbe3d685eebab0e62d49501e34e8c37ee52bc8e66fcc7a113c348777> (15)
  *   M Views/Issues/Index.cshtml<https://github.com/noellopes/Supermarket/pull/59/files#diff-b26a9a66f10199b0abffa9a1b02a7625338d15225524ed23fed63090124f3de3> (18)
  *   A Views/ProductExpirations/DeleteCompleted.cshtml<https://github.com/noellopes/Supermarket/pull/59/files#diff-2b9528a6e7cdaa20249c7ada01520e0a599a362bd5d85ebe1363d2c39bf24e0b> (34)
  *   A Views/ProductExpirations/ProductExpirationDeleted.cshtml<https://github.com/noellopes/Supermarket/pull/59/files#diff-6d7ba297fd3411eeb85e3bc6b6793339e1fd07c19a3e880e25f4a08164ffefae> (10)

Patch Links:

  *   https://github.com/noellopes/Supermarket/pull/59.patch
  *   https://github.com/noellopes/Supermarket/pull/59.diff

**Comment by eduardoparaiso** [comment]
@Andredzao, não há necessidade de tabelas intermediarias, é no mesmo estilo autor-livro das aulas. No caso, um produto ou funcionario pode ter varias issues associadas, mas cada issue só pode ter um produto ou funcionario. A tabela intermediaria seria necessário em uma relação N-N. Como no caso o modelo de vocês são a relação N e são elas que recebem um ICollection, por isso que necessito apenas que no modelos de vocês haja uma ICollection para o meu modelo.

**Comment by Andredzao** [comment]
Ok, agradeço a explicação, penso que percebi, vou proceder à autorização do pull request.

________________________________
De: Eduardo Paraíso ***@***.***>
Enviado: 14 de dezembro de 2023 18:49
Para: noellopes/Supermarket ***@***.***>
Cc: André Antunes ***@***.***>; Mention ***@***.***>
Assunto: Re: [noellopes/Supermarket] Pull Request Grupo 9 com revisão pelo grupo 4 e 7 (PR #59)


@Andredzao<https://github.com/Andredzao>, não há necessidade de tabelas intermediarias, é no mesmo estilo autor-livro das aulas. No caso, um produto ou funcionario pode ter varias issues associadas, mas cada issue só pode ter um produto ou funcionario. A tabela intermediaria seria necessário em uma relação N-N. Como no caso o modelo de vocês são a relação N e são elas que recebem um ICollection, por isso que necessito apenas que no modelos de vocês haja uma ICollection para o meu modelo.

**Comment by Andredzao** [comment]
Não consigo aceitar o pull request, pois está a dar conflito (imagen anexada), tem problema se não aceitar o pull request e esperar pela proxima aula para pedir ajuda ao professor?
________________________________
De: Eduardo Paraíso ***@***.***>
Enviado: 14 de dezembro de 2023 18:49
Para: noellopes/Supermarket ***@***.***>
Cc: André Antunes ***@***.***>; Mention ***@***.***>
Assunto: Re: [noellopes/Supermarket] Pull Request Grupo 9 com revisão pelo grupo 4 e 7 (PR #59)


@Andredzao<https://github.com/Andredzao>, não há necessidade de tabelas intermediarias, é no mesmo estilo autor-livro das aulas. No caso, um produto ou funcionario pode ter varias issues associadas, mas cada issue só pode ter um produto ou funcionario. A tabela intermediaria seria necessário em uma relação N-N. Como no caso o modelo de vocês são a relação N e são elas que recebem um ICollection, por isso que necessito apenas que no modelos de vocês haja uma ICollection para o meu modelo.

**Comment by eduardoparaiso** [comment]
@Andredzao sem problemas, esta funcionando na minha branch. Queria apenas que os grupos responsáveis pelos modelos ficassem cientes da modificação que eu precisava fazer. Obrigado

**Pull request closed without merging**
